musicDict = {
    '博丽灵梦': ['东方妖恋谈', '少女绮想曲_～_Capriccio', '春色小径_～_Colorful_Path', '二色莲花蝶_～_Ancients'],
    '雾雨魔理沙': ['恋色Magic', 'Dim._Dream', '星之器_～_Casket_of_Star', '魔女们的舞会', 'Oriental_Dark_Flight', 'Magus_Night'],
    '神玉': ['The_Positive_and_Negative'],
    '魅魔': ['天使传说', 'Complete_Darkness', 'Reincarnation'],
    '菊理&依莉斯': ['魔镜'],
    '矜羯罗': ['星幽剑士'],
    '幽幻魔眼': ['天使传说'],
    '萨丽爱尔': ['来吧，直到倒地死去的那一刻', '同归于尽'],
    '里香': ['She\'s_in_a_temper!!', '战车娘所做的梦'],  # She's in a temper!!有14首，但查询规则没有找到准确，这个需要手动加
    '明罗': ['黑暗的力量'],
    '爱莲': ['Tabula_rasa_～_空白少女'],
    '小兔姬': ['Maniacal_Princess'],
    '卡娜·安娜贝拉尔': ['梦消失_～_Lost_Dream'],
    '朝仓理香子': ['梦幻游戏_～_Dream_War'],
    '北白河千百合': ['Sailor_of_Time'],
    '冈崎梦美': ['Strawberry_Crisis!!'],
    '奥莲姬': ['装饰战_～_Decoration_Battle'],
    '胡桃': ['红响曲_～_Scarlet_Phoneme'],
    '艾丽': ['灵战_～_Perdition_crisis'],
    # '幽香(旧作)': ['沉睡的恐怖_～_Sleeping_Terror', '幽梦_～_Inanimate_Dream'],
    '梦月': ['女仆幻想_～_Icemilk_Magic'],
    '幻月': ['可爱的恶魔_～_Innocence'],
    '萨拉': ['魔法阵_～_Magic_Square'],
    '露易兹': ['灵天_～_Spiritual_Heaven'],
    '雪': ['禁忌的魔法_～_Forbidden_Magic', '绯红的少女_～_Crimson_Dead!!'],
    '舞': ['禁忌的魔法_～_Forbidden_Magic', '背叛的少女_～_Judas_Kiss'],
    '梦子': ['可悲的人偶_～_Doll_of_Misery'],
    '神绮': ['神话幻想_～_Infinite_Being'],
    '露米娅': ['妖魔夜行'],
    # '大妖精': [''],
    '琪露诺': ['活泼纯情小姑娘的冒险'],
    '红美铃': ['明治十七年的上海爱丽丝', '上海红茶馆_～_Chinese_Tea'],
    # '小恶魔': [''],
    '帕秋莉·诺蕾姬': ['Locked_Girl_～_少女密室', '巴瓦鲁魔法图书馆'],
    '十六夜咲夜': ['月时计_～_Luna_Dial', '女仆与血之怀表', 'Flowering_Night'],
    '蕾米莉亚·斯卡蕾特': ['献给已逝公主的七重奏'],
    '芙兰朵露·斯卡蕾特 ': ['U.N.OWEN就是她吗？'],
    '蕾蒂·霍瓦特洛克': ['Crystallize_Silver'],
    '橙': ['凋叶棕（withered_leaf）'],
    '爱丽丝·玛格特洛依德': ['布加勒斯特的人偶师', '人偶裁判', 'the_Grimoire_of_Alice', 'Plastic_Mind'],
    # '莉莉霍瓦特': [],
    '骚灵三姐妹': ['幽灵乐团_～_Phantom_Ensemble'],
    '魂魄妖梦': ['广有射怪鸟事_～_Till_When%3F', '东方妖妖梦_～_Ancient_Temple'],
    '西行寺幽幽子': ['幽雅地绽放吧，墨染的樱花_～_Border_of_Life', 'Border_of_Life', 'Ghost_Lead'],
    '八云蓝': ['少女幻葬_～_Necro-Fantasy'],
    '八云紫': ['Necro-Fantasia', '夜幕降临', '凭坐处于梦与现实之间_～_Necro-Fantasia'],
    '伊吹萃香': ['御伽之国的鬼岛_～_Missing_Power', '碎月'],
    '莉格露·奈特巴格': ['蠢蠢的秋月_～_Mooned_Insect'],
    '米斯蒂娅·萝蕾拉': ['已经只能听见歌声了_～_Flower_Mix'],
    '上白泽慧音': ['Plain_Asia'],
    '因幡帝': ['宇佐大人的白旗'],
    '铃仙·优昙华院·因幡': ['狂气之瞳_～_Invisible_Full_Moon'],
    '八意永琳': ['千年幻想乡_～_History_of_the_Moon'],
    '蓬莱山辉夜': ['竹取飞翔_～_Lunatic_Princess'],
    '藤原妹红': ['飘上月球，不死之烟'],
    '射命丸文': ['风神少女(Short_Version)', '妖怪之山_～_Mysterious_Mountain'],
    '梅蒂欣·梅兰可莉': ['剧毒身体_～_Forsaken_Doll'],
    '风见幽香': ['今昔幻想乡_～_Flower_Land', '沉睡的恐怖_～_Sleeping_Terror', '幽梦_～_Inanimate_Dream'],
    '小野塚小町': ['彼岸归航_～_Riverside_View'],
    '四季映姬·亚玛撒那度': ['第六十年的东方审判_～_Fate_of_Sixty_Years'],
    # '秋静叶': [''],
    '秋穰子': ['会受稻田姬的斥责啦'],
    '键山雏': ['命运的阴暗面'],
    '河城荷取': ['芥川龙之介的河童_～_Candid_Friend'],
    # '犬走椛': [''],
    '东风谷早苗': ['信仰是为了虚幻之人'],
    '八坂神奈子': ['神圣庄严的古战场_～_Suwa_Foughten_Field'],
    '洩矢诹访子': ['Native_Faith', '明日之盛，昨日之俗'],
    '永江衣玖': ['黑海中的绯红_～_Legendary_Fish'],
    '比那名居天子': ['有顶天变_～_Wonderful_Heaven', '幼小的有顶天'],
    # '琪斯美': [''],
    '黑谷山女': ['被封印的妖怪_～_Lost_Place'],
    '水桥帕露西': ['绿眼的嫉妒'],
    '星熊勇仪': ['大江山的花之酒宴'],
    '古明地觉': ['少女觉_～_3rd_eye'],
    '火焰猫燐': ['尸体旅行_～_Be_of_good_cheer!'],
    '灵乌路空': ['灵知的太阳信仰_～_Nuclear_Fusion'],
    '古明地恋': ['哈德曼的妖怪少女'],
    '娜兹玲': ['小小的贤将'],
    '多多良小伞': ['请注意万年备用伞'],
    '云居一轮&云山': ['守旧老爹与前卫少女'],
    '村纱水蜜': ['Captain_Murasa'],
    '寅丸星': ['虎纹的毘沙门天'],
    '圣白莲': ['感情的摩天楼_～_Cosmic_Mind'],
    '封兽鵺': ['平安时代的外星人'],
    # '姬海棠果': [''],
    '幽谷响子': ['门前的妖怪小姑娘'],
    '宫古芳香': ['Rigid_Paradise'],
    '霍青娥': ['古老的元神'],
    # '苏我屠自古': [''],
    '物部布都': ['大神神话传'],
    '丰聪耳神子': ['圣德传说_～_True_Administrator'],
    '二岩猯藏': ['佐渡的二岩', '幻想乡的二岩'],
    '秦心': ['亡失的情感'],
    '若鹭姬': ['秘境的人鱼'],
    '赤蛮奇': ['柳树下的杜拉罕'],
    '今泉影狼': ['孤独的狼人'],
    '九十九弁弁&九十九八桥': ['幻想净琉璃'],
    '鬼人正邪': ['Reverse_Ideology'],
    '少名针妙丸': ['辉光之针的小人族_～_Little_Princess'],
    '堀川雷鼓': ['原初的节拍_～_Pristine_Beat'],
    '宇佐见堇子': ['Last_Occultism_～_现世的秘术师'],
    '清兰': ['兔已着陆'],
    '铃瑚': ['九月的南瓜'],
    '哆来咪·苏伊特': ['永远的春梦'],
    '稀神探女': ['逆转的命运之轮'],
    '克劳恩皮丝': ['星条旗的小丑'],
    '纯狐': ['Pure_Furies_～_心之所在'],
    '赫卡提亚·拉碧斯拉祖利': ['Pandemonic_Planet'],
    '依神女苑&依神紫苑': ['今宵是飘逸的自我主义者(Live_ver)_～_Egoistic_Flowers.'],
    '爱塔妮缇拉尔瓦': ['仲夏的妖精梦'],
    '坂田合欢': ['深山的遭遇'],
    '高丽野阿吽': ['一对的神兽'],
    '矢田寺成美': ['魔法的笠地藏'],
    '尔子田里乃&丁礼田舞': ['Crazy_Back_Dancers'],
    '摩多罗隐岐奈': ['被秘匿的四个季节', '秘神摩多罗_～_Hidden_Star_in_All_Seasons.'],
    '戎璎花': ['Jelly_Stone'],
    '牛崎润美': ['石之婴儿与水中牛'],
    '庭渡久侘歌': ['Seraphic_Chicken'],
    '吉吊八千慧': ['Tortoise_Dragon_～_幸运与不幸'],
    '杖刀偶磨弓': ['陶瓷的杖刀人'],
    '埴安神袿姬': ['寄世界于偶像_～_Idoratrize_World'],
    '骊驹早鬼': ['圣德太子的天马_～_Dark_Pegasus'],
    '桑尼米尔克': ['妖精大战争_～_Fairy_Wars', 'Sunny_Rutile_Flection', '赌上性命去恶作剧'],
    '露娜切露德': ['妖精大战争_～_Fairy_Wars', '因夜失眠', '赌上性命去恶作剧'],
    '斯塔萨菲雅': ['妖精大战争_～_Fairy_Wars', '妖精灿烂的样子', '赌上性命去恶作剧'],
    '茨木华扇': ['华狭间的战场'],
}
